### ISSUE TITLE
Display TVL

### ISSUE THREAD

**Issue by tomjohn1028** [mithraiclabs/bi-dashboard#1]
Chart Type: Number

### Why it's needed
- Shows the "Total Value Locked" within the protocol
- Great for measuring protocol growth and success
- The perfect marketing tool

### How to get the data
1. Load all `OptionMarket`s from PsyAmerican protocol [see docs](https://docs.psyoptions.io/javascript-api/modules#getalloptionaccounts)
````TypeScript
// THIS IS DETAILED PSEUDO CODE AND WILL NOT WORK COPY PASTA

import { Keypair, PublicKey } from '@solana/web3.js';
import { PsyAmericanIdl } from "@mithraic-labs/psy-american";

const connection = new Connection("https://api.mainnet-beta.solana.com");
const anchorProvider = new Provider(connection, new Keypair(), {});
const program = new Program(PsyAmericanIdl, new PublicKey('R2y9ip6mxmWUj4pt54jP2hz2dgvMozy9VTSwMWE7evs'), anchorProvider);
// Load all the PsyOptions option markets
const optionMarkets = await getAllOptionAccounts(program);
````
2. Group the _underlyingAssetPool_s and _quoteAssetPool_s by their mint addresses. Then sum the total amount in all of the pools for each asset type. (E.g. in all pools across all markets there is 115 BTC, 234 ETH, and 5,000,000 USDC)

3. Use Aleph's API to query the current price of the asset by the mint address (E.g. current price of BTC on Serum). Using the mint address rather than hard coding these values makes this scaleable as OptionMarkets are permissionless and may have random assets added.

4. Multiply the amounts of assets in the pools with the price of the assets and sum all.

**Comment by devexpert127** [comment]
getAllOptionAccounts() method doesn't accept Program<Idl> variable as a parameter

**Comment by tomjohn1028** [comment]
Yeah it does, here's the [source](https://github.com/mithraiclabs/psyoptions-ts/blob/master/packages/psy-american/src/OptionMarket.ts#L10)

**Comment by devexpert127** [comment]
const program = new Program(PsyAmericanIdl, new PublicKey('R2y9ip6mxmWUj4pt54jP2hz2dgvMozy9VTSwMWE7evs'), anchorProvider);

The type of program is Program<Idl>
getAllOptionAccounts() method accepts Program

**Comment by devexpert127** [comment]
const program = new Program(PsyAmericanIdl, new PublicKey('R2y9ip6mxmWUj4pt54jP2hz2dgvMozy9VTSwMWE7evs'), anchorProvider);

The type of program is Program<Idl>
getAllOptionAccounts() method accepts Program

**Comment by tomjohn1028** [comment]
> const program = new Program(PsyAmericanIdl, new PublicKey('R2y9ip6mxmWUj4pt54jP2hz2dgvMozy9VTSwMWE7evs'), anchorProvider);
>
> The type of program is Program
> getAllOptionAccounts() method accepts Program

@devexpert127 I'm not sure I understand this comment. Is there a question for me to address?

**Comment by devexpert127** [comment]
![image](https://user-images.githubusercontent.com/88482396/145373998-0f16f470-d355-4721-a53b-92e1be2a3686.png)
Current version shows TVL of quote asset and underlying assets per mint address.

c44a827480e15743e5e826ff30418d42eade6bf6

**Comment by tomjohn1028** [comment]
@devexpert127 this looks awesome!! Could they be combined so we can see totals across underlying asset pools and quote asset pools?

Instead of a Barchart what do you think about a pie chart? 
See how Mango uses the pie charts to give a good indication of cumulative value across all assets 

https://mango.metabaseapp.com/public/dashboard/e312fbc8-9507-458c-a0e4-fb882c36b0d6

**Comment by devexpert127** [comment]
![image](https://user-images.githubusercontent.com/88482396/145462971-36fce3b8-d7f1-442f-8d62-ce93358f2b40.png)
This is updated version with pie chart.

**Comment by tomjohn1028** [comment]
@devexpert127 This looks great! Will it show the grand total when the user is not hovering over one slice? And can we have it display for both underlying and quote asset pools? We don't want them to be separated because we want to see total TVL in the protocol.

**Comment by devexpert127** [comment]
![image](https://user-images.githubusercontent.com/88482396/145468056-80141cfa-2d22-4bbf-a628-1410214a80b2.png)
This is updated with chart, currency, and merged asset pools

**Comment by tomjohn1028** [comment]
@devexpert127 Amazing! 1 last tweak, could we add commas to the Total and drop the floating point (make it an integer that is the floor)?

**Comment by devexpert127** [comment]
![image](https://user-images.githubusercontent.com/88482396/145471385-5ebac61a-a653-4130-87e2-c0fc6815dc86.png)
Update with comma, drop floating points

**Comment by devexpert127** [comment]
node packages are updated
