### ISSUE TITLE
Unique Daily Traders

### ISSUE THREAD

**Issue by tomjohn1028** [mithraiclabs/bi-dashboard#4]
Chart Type: Line Graph

Number of unique daily traders spanning the last 30 days

### Primary Data Source
* Aleph
Example Query where "au" stands for Active User
````
{
  dailyStats(markets: ARRAY_OF_MARKETS
)
    {
    au {
      au
      interval
    }
  }
}
````

#### Example chart 
Note: The chart below contains the volume (as a bar chart) as well, which is not required at the moment. 

<img width="1780" alt="Screen Shot 2021-12-06 at 11 39 11 AM" src="https://user-images.githubusercontent.com/32071703/144911109-a42fa5b8-1ee2-45f5-9ed1-5501339bd426.png">

**Comment by devexpert127** [comment]
![image](https://user-images.githubusercontent.com/88482396/146221107-702495ca-35d2-4e61-8cb9-48e4418a0918.png)
It has only 7d trade data
Could you please let me know how to get 30 day

**Comment by tomjohn1028** [comment]
@devexpert127 See the example query and the use of `au`. You can test it [here](https://api.serum.markets/)

**Comment by devexpert127** [comment]
I've tested it. is it same as group by quotemintaddress and underlyingmintaddress?

**Comment by tomjohn1028** [comment]
>I've tested it. is it same as group by quotemintaddress and underlyingmintaddress? 

I think 1 request that uses all of the Serum markets, so we know how many users are using PsyOptions in general.

**Comment by devexpert127** [comment]
Okay got it

**Comment by devexpert127** [comment]
https://github.com/mithraiclabs/bi-dashboard/pull/6

![image](https://user-images.githubusercontent.com/88482396/146265841-e19d7c4b-ba9c-49ac-a6a4-f7274723613d.png)
